name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker for Selenium and Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl unzip

    - name: Pull and run Selenium Docker container
      run: |
        docker run -d -p 4444:4444 --name selenium-server selenium/standalone-chrome:latest

    - name: Wait for Selenium to be ready
      run: |
        sleep 10

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Run tests
      run: |
        dotnet test /home/runner/work/testFrameForSymphony/testFrameForSymphony/TestProject.sln --configuration Debug

    - name: Stop and remove the Selenium Docker container
      run: |
        docker stop selenium-server
        docker rm selenium-server